import random

PROFESSIONS = [
    "Accountant",
    "Actor",
    "Athlete",
    "Author",
    "Chef",
    "Engineer",
    "Entrepreneur",
    "Nurse",
    "Photographer",
    "Scientist",
    "Teacher",
]

HOUSEGUEST_PROFESSIONS = {
    "US2": {
        "Will": "Doctor",
        "Nicole": "Personal Chef",
        "Hardy": "Basketball Player",
        "Krista": "Waitress",
        "Justin": "Bartender",
        "Shannon": "Nurse",
        "Autumn": "Student",
        "Mike": "Bar Owner",
        "Sheryl": "Actress",
        "Kent": "Mortgage Broker",
        "Bunky": "Waiter",
        "Monica": "Candy Store Manager",
    },
    "US3": {
        "Danielle": "Media Buyer",
        "Jason": "Videographer",
        "Lisa": "Bartender",
        "Marcellas": "Fashion Stylist",
        "Amy": "Real Estate Appraiser",
        "Roddy": "Writer",
        "Chiara": "Songwriter",
        "Gerry": "Teacher",
        "Josh": "Waiter",
        "Tonya": "Retail Manager",
        "Eric": "Firefighter",
        "Lori": "Yoga Instructor",
    },
    "US4": {
        "Jun": "Investment Manager",
        "Alison": "Retail Sales Manager",
        "Robert": "Restaurant Manager",
        "Erika": "Pilates Instructor",
        "Jack": "FBI Agent",
        "Nathan": "Accountant",
        "Dana": "Karate School Owner",
        "Jee": "Bookkeeper",
        "Justin": "Headhunter",
        "Scott": "Debt Collector",
        "Amanda": "Bar Manager",
        "David": "Former Army Ranger",
        "Michelle": "Mortgage Loan Officer",
    },
    "US5": {
        "Drew": "Recent College Graduate",
        "Michael": "Security Officer",
        "Diane": "Cocktail Waitress",
        "Nakomis": "Restaurant Hostess",
        "Cowboy": "Security Officer",
        "Adria": "Web Designer",
        "Natalie": "Tarot Card Reader",
        "Karen": "Portrait Artist",
        "Will": "Registered Nurse",
        "Jase": "Volunteer Firefighter",
        "Marvin": "Mortician",
        "Holly": "Model",
        "Mike": "Painter",
        "Lori": "Yoga Instructor",
    },
    "US6": {
        "Maggie": "ER Nurse",
        "Ivette": "Waitress",
        "Janelle": "VIP Cocktail Waitress",
        "April": "Pharmaceutical Sales Representative",
        "Howie": "Jedi",
        "Kaysar": "Graphic Designer",
        "Jennifer": "Arena Football Dancer",
        "Rachel": "Horse Breeder",
        "James": "Loss Prevention Manager",
        "Sarah": "Retail Manager",
        "Beau": "Personal Shopper",
        "Eric": "Talent Management Assistant",
        "Ashlea": "Clothing Designer",
        "Michael": "Artist",
    },
    "US7": {
        "Mike": "Commercial Painter",
        "Erika": "Pilates Instructor",
        "Janelle": "VIP Cocktail Waitress",
        "Will": "Registered Nurse",
        "Danielle": "Media Buyer",
        "George": "Retired",
        "James": "Loss Prevention Manager",
        "Howie": "Jedi",
        "Marcellas": "Fashion Stylist",
        "Nakomis": "Restaurant Hostess",
        "Diane": "Cocktail Waitress",
        "Jase": "Volunteer Firefighter",
        "Alison": "Retail Sales Manager",
        "Kaysar": "Graphic Designer",
    },
    "US8": {
        "Dick": "Bar Manager",
        "Daniele": "Waitress",
        "Zach": "Graphic Designer",
        "Jameka": "School Counselor",
        "Eric": "New York Firefighter",
        "Jessica": "Freelance Writer",
        "Amber": "Cocktail Waitress",
        "Dustin": "Shoe Store Manager",
        "Jen": "Nanny",
        "Nick": "Former Pro Football Player",
        "Kail": "Business Owner",
        "Mike": "Painting Contractor",
        "Carol": "Student",
        "Joe": "Receptionist",
    },
    "US9": {
        "Adam": "PR Manager",
        "Ryan": "College Student",
        "Sheila": "Elementary School Teacher",
        "Sharon": "Realtor",
        "James": "Retail Sales",
        "Chelsia": "College Student",
        "Joshuah": "Advertising Media Buyer",
        "Natalie": "Bikini Barista",
        "Matt": "Roofing Foreman",
        "Allison": "Pharmaceutical Sales Representative",
        "Alex": "DJ",
        "Amanda": "Paralegal",
        "Parker": "Paparazzo",
        "Neil": "Real Estate Appraiser",
        "Jacob": "Receptionist",
    },
    "US10": {
        "Dan": "Catholic School Teacher",
        "Memphis": "Mixologist",
        "Jerry": "Marine Corps Chef",
        "Keesha": "Waitress",
        "Renny": "Beauty Salon Owner",
        "April": "Pharmaceutical Sales Representative",
        "Ollie": "Marketing Sales Representative",
        "Michelle": "Real Estate Agent",
        "Libra": "Human Resources Representative",
        "Jessie": "Bodybuilder",
        "Angie": "Student",
        "Steven": "Geographic Consultant",
        "Brian": "Telecommunication Account Manager",
    },
    "US11": {
        "Jordan": "Waitress",
        "Natalie": "Tae Kwon Do Champion",
        "Kevin": "Graphic Designer",
        "Michele": "Neuroscientist",
        "Jeff": "Advertising Salesman",
        "Russell": "Mixed Martial Arts Fighter",
        "Lydia": "Special Effects Makeup Artist",
        "Jessie": "Bodybuilder",
        "Chima": "Freelance Journalist",
        "Ronnie": "Video Game Expert",
        "Casey": "Fifth Grade Teacher",
        "Laura": "Bikini Model",
        "Braden": "Surfer",
    },
    "US12": {
        "Hayden": "College Student",
        "Lane": "Oil Rig Salesman",
        "Enzo": "Insurance Adjuster",
        "Britney": "Hotel Sales Manager",
        "Ragan": "College Professor",
        "Matt": "Web Designer",
        "Brendon": "High School Swim Coach",
        "Kathy": "Deputy Sheriff",
        "Rachel": "Chemist",
        "Andrew": "Podiatrist",
        "Kristen": "Shoe Boutique Manager",
        "Monet": "Model",
        "Annie": "Bartender",
    },
    "US13": {
        "Rachel": "Chemist",
        "Porsche": "VIP Cocktail Waitress",
        "Adam": "Music Industry Manager",
        "Kalia": "Writer",
        "Shelly": "Outdoors Industry Executive",
        "Jordan": "Waitress",
        "Jeff": "Advertising Salesman",
        "Daniele": "Waitress",
        "Brendon": "High School Swim Coach",
        "Lawon": "Legal File Clerk",
        "Dominic": "College Student",
        "Cassi": "Model",
        "Keith": "Human Resources Manager",
    },
    "US14": {
        "Ian": "Engineering Student",
        "Dan": "Catholic School Teacher",
        "Danielle": "Nurse",
        "Shane": "House Flipper",
        "Jenn": "Musician",
        "Frank": "Unemployed",
        "Joe": "Chef",
        "Ashley": "Spray Tan Technician",
        "Wil": "Marketing Consultant",
        "Janelle": "VIP Cocktail Waitress",
        "Mike": "DJ",
        "Britney": "Hotel Sales Manager",
        "Willie": "Tank Assembly Foreman",
        "JoJo": "Bartender",
    },
    "US15": {
        "Andy": "Public Speaking Professor",
        "GinaMarie": "Pageant Coordinator",
        "Spencer": "Railroad Conductor",
        "Judd": "Property Appraiser",
        "McCrae": "Pizza Delivery Boy",
        "Amanda": "Real Estate Agent",
        "Elissa": "Nutritionist",
        "Helen": "Political Consultant",
        "Aaryn": "College Student",
        "Jessie": "Unemployed",
        "Candice": "Pediatric Speech Therapist",
        "Howard": "Youth Counselor",
        "Kaitlin": "Bartender",
        "Jeremy": "Boat Shop Associate",
        "Nick": "Entrepreneur",
        "David": "Lifeguard",
    },
    "US16": {
        "Derrick": "Police Sergeant",
        "Cody": "Sales Account Executive",
        "Victoria": "Photographer",
        "Caleb": "Adventure Hunting Guide",
        "Frankie": "YouTube Personality",
        "Zach": "Recent College Graduate",
        "Donny": "School Groundskeeper",
        "Christine": "Barista",
        "Nicole": "Recent Nursing Graduate",
        "Hayden": "Pedicab Driver",
        "Jocasta": "Minister",
        "Amber": "Esthetician",
        "Brittany": "Event Coordinator",
        "Devin": "Former Professional Baseball Player",
        "Paola": "DJ",
        "Joey": "Makeup Artist",
    },
    "US17": {
        "Steve": "Former College Student",
        "Liz": "Marketing Coordinator",
        "Vanessa": "Poker Dealer",
        "Austin": "Professional Wrestler",
        "Julia": "College Student",
        "James": "Retail Associate",
        "Meg": "Server",
        "Jackie": "Travel Agent",
        "Becky": "Retail Manager",
        "Shelli": "Interior Designer",
        "Clay": "Graduate Student",
        "John": "Dentist",
        "Jason": "Supermarket Cashier",
        "Audrey": "Digital Media Consultant",
        "Jeff": "Sales Associate",
        "Da'Vonne": "Poker Dealer",
        "Jace": "Personal Trainer",
    },
    "US18": {
        "Nicole": "ER Nurse",
        "Paul": "Clothing Designer",
        "James": "Veteran",
        "Natalie": "Event Coordinator",
        "Corey": "Baseball Coach",
        "Paulie": "DJ",
        "Michelle": "Nutritionist",
        "Zakiyah": "Preschool Teacher",
        "Bridgette": "Traveling Nurse",
        "Da'Vonne": "Poker Dealer",
        "Victor": "Gym Manager",
        "Bronte": "Student",
        "Tiffany": "High School Teacher",
        "Frank": "Medical Sales Representative",
        "Glenn": "Dog Groomer and Former Police Detective",
        "Jozea": "Makeup Artist",
    },
    "US19": {
        "Josh": "Hair Care Sales",
        "Paul": "Clothing Designer",
        "Christmas": "Fitness Superstar",
        "Kevin": "Stay-at-Home Dad",
        "Alex": "Eco-Friendly Marketing Rep",
        "Jason": "Rodeo Clown",
        "Raven": "Dance Teacher",
        "Matt": "Renovation Consultant",
        "Mark": "Personal Trainer",
        "Elena": "Radio Personality",
        "Cody": "Construction Sales Rep",
        "Jessica": "VIP Concierge",
        "Ramses": "Cosplay Artist",
        "Dominique": "Government Engineer",
        "Jillian": "Timeshare Sales Rep",
        "Megan": "Dog Walker",
        "Cameron": "Microbiologist",
    },
    "US20": {
        "Kaycee": "Pro Football Player",
        "Tyler": "Lifeguard",
        "JC": "Professional Dancer",
        "Angela": "Fitness Model",
        "Sam": "Welder",
        "Brett": "Cyber Security Engineer",
        "Haleigh": "College Student",
        "Faysal": "Substitute Teacher",
        "Scottie": "Shipping Manager",
        "Rockstar": "Pagan Witch",
        "Bayleigh": "Flight Attendant",
        "Rachel": "Las Vegas Entertainer",
        "Kaitlyn": "Life Coach",
        "Swaggy C": "Day Trader",
        "Winston": "Medical Sales Rep",
        "Steve": "Former Undercover Cop",
    },
    "US21": {
        "Jackson": "Server",
        "Holly": "Wine Safari Guide",
        "Nicole": "Preschool Aide",
        "Cliff": "Petroleum Engineer",
        "Tommy": "Broadway Dancer",
        "Christie": "Boutique Owner",
        "Nick": "Therapist",
        "Analyse": "College Soccer Star",
        "Jessica": "Model",
        "Kathryn": "Digital Marketing Executive",
        "Jack": "Fitness Trainer",
        "Sis": "Public Health Analyst",
        "Sam": "Truck Driver",
        "Bella": "College Student",
        "Ovi": "College Student",
        "Kemi": "Marketing Strategist",
        "David": "Photographer",
    },
    "US22": {
        "Cody": "Soccer Coach",
        "Enzo": "Insurance Adjuster",
        "Nicole F": "Podcast Host",
        "Christmas": "Fitness Entrepreneur",
        "Memphis": "Restaurateur",
        "Tyler": "Jewelry Company Owner",
        "David": "Senior Sales Representative",
        "Dani": "Stay-at-Home Mom",
        "Kevin": "Ad Agency Executive",
        "Da'Vonne": "Acting Coach",
        "Ian": "Management Consultant",
        "Bayleigh": "Model",
        "Kaysar": "Biotech Executive",
        "Janelle": "Real Estate Agent",
        "Nicole A": "Podcast Host",
        "Keesha": "Waitress",
    },
    "US23": {
        "Xavier": "Attorney",
        "Derek F": "Safety Officer",
        "Azah": "Director of Sales Operations",
        "Kyland": "Account Executive",
        "Hannah": "Graduate Student",
        "Tiffany": "Phlebotomist",
        "Claire": "Artificial Intelligence Engineer",
        "Alyssa": "Swimwear Designer",
        "Sarah Beth": "Forensic Scientist",
        "Derek X": "Start-Up Founder",
        "Britini": "Kindergarten Teacher",
        "Christian": "General Contractor Assistant",
        "Whitney": "Make-Up Artist",
        "Brent": "Flight Attendant",
        "Brandon": "Auto Sales",
        "Travis": "Tech Sales Consultant",
    },
    "CA1": {
        "Jillian": "Teacher",
        "Gary": "Bartender",
        "Emmett": "Dairy Farmer",
        "Talla": "Real Estate Agent",
        "Andrew": "Restaurant Manager",
        "Topaz": "Dental Hygienist",
        "Alec": "Psychic",
        "Peter": "Web Content Curator",
        "Liza": "Tanning Salon Owner",
        "Tom": "Firefighter",
        "Suzette": "Support Worker",
        "Danielle": "Nurse",
        "Aneal": "Law Student",
        "Kat": "Bartender",
        "AJ": "Bartender",
    },
    "CA2": {
        "Jon": "Contractor",
        "Neda": "Fashion Stylist",
        "Sabrina": "Makeup Artist",
        "Heather": "Model Agency Coordinator",
        "Adel": "Welder",
        "Allison": "Registered Nurse",
        "Arlie": "Unemployed",
        "Rachelle": "Student",
        "Ika": "Financial Services Representative",
        "Kenny": "Nurse",
        "Paul": "Clothing Designer",
        "Sarah": "Mother of Two",
        "Kyle": "Freelance Writer",
        "Andrew": "Pharmacy Student",
    },
    "CA3": {
        "Sarah": "Mortgage Broker",
        "Godfrey": "Psychology Student",
        "Ashleigh": "Escort Agency Concierge",
        "Pilar": "Student",
        "Zach": "Pharmaceutical Sales Rep",
        "Bruno": "Inventor",
        "Kevin": "Poker Player",
        "Willow": "Flight Attendant",
        "Brittnee": "Meat Clerk",
        "Johnny": "Dentist",
        "Jordan": "Petroleum Engineering Student",
        "Sindy": "Hair Stylist",
        "Naeha": "Real Estate Agent",
        "Graig": "Art Director",
        "Risha": "Supply Teacher",
    },
    "CA4": {
        "Nick & Phil": "Brothers",
        "Kelsey": "Flight Attendant",
        "Tim": "Philosopher",
        "Cassandra": "Dancer",
        "Joel": "Firefighter",
        "Loveita": "Entrepreneur",
        "Nikki": "Makeup Artist",
        "Jared": "Firefighter",
        "Maddy": "Law Student",
        "Ramsey": "Renovation Contractor",
        "Dallas": "Lobster Fisherman",
        "Raul": "Jewelry Store Manager",
        "Mitch": "Psychiatrist",
        "Christine": "Barista",
        "Paige": "Mortgage Broker",
        "Sharry": "Stay-at-Home Mom",
        "Veronica": "Waitress",
    },
    "CA5": {
        "Kevin": "Poker Player",
        "Karen": "Real Estate Broker",
        "Demetres": "Oil Field Instrument Technician",
        "Ika": "Financial Services Manager",
        "Dillon": "Musician",
        "Dre": "Masters Student",
        "William": "Marketing Student",
        "Jackie": "Intervention Youth Worker",
        "Sindy": "Beauty Queen",
        "Bruno": "Construction Worker",
        "Neda": "Fashion Stylist",
        "Emily": "Model",
        "Cassandra": "Free Spirit",
        "Gary": "Tennis Coach",
        "Dallas": "Lobster Fisherman",
        "Mark": "Bartender",
    },
    "CA6": {
        "Paras": "Student",
        "Kaela": "Wine Ambassador",
        "Derek": "Retired Athlete",
        "Will": "Bartender",
        "Maddy": "Venue Coordinator",
        "Johnny": "Sales Rep",
        "Olivia": "Recruitment Consultant",
        "Ali": "Personal Trainer",
        "Erica": "Server",
        "Hamza": "Soccer Player",
        "Jesse": "Gardener",
        "Veronica": "Waitress",
        "Merron": "Events Coordinator",
        "Rozina": "Religious Scholar",
        "Andrew": "Demolition Company Employee",
    },
    "CA7": {
        "Dane": "Civil Engineer",
        "Anthony": "Gas Inspector",
        "Kyra": "Bartender",
        "Mark": "Bartender",
        "Adam": "Human Resources Manager",
        "Sam": "Truck Driver",
        "Este": "Actress",
        "Damien": "Warehouse Worker",
        "Kiki": "Alcohol Sales Rep",
        "Cory": "Flight Attendant",
        "Chelsea": "Waitress and Actress",
        "Eddie": "Musician",
        "Kailyn": "Life Coach",
        "Maki": "Cryptocurrency Investor",
        "Laura": "Economist",
    },
    # Add the remaining seasons and their respective houseguests' professions
    # ...
}


class HouseGuest:

    def __init__(self, name, lmode=False):
        # Generate random age and profession
        self.age = random.randint(21, 40)

        self.profession = None

        if isinstance(lmode, str):
            if lmode in HOUSEGUEST_PROFESSIONS:
                if name in HOUSEGUEST_PROFESSIONS[lmode]:
                    self.profession = HOUSEGUEST_PROFESSIONS[lmode][name]

        if self.profession == None:
            self.profession = random.choice(PROFESSIONS)

        self.name = name
        self.HOH = False
        self.nominee = False
        self.veto = False
        self.vetoed = False
        self.target = None
        self.impressions = {}
        self.alliances = []

        self.friendliness = random.randint(1, 5)
        self.loyalty = random.randint(1, 5)
        self.manipulativeness = random.randint(1, 5)
        self.emotionality = random.randint(1, 5)
        self.competitiveness = random.randint(1, 5)

    def __repr__(self):
        return self.name

    def summary(self):
        """Return a string with the houseguest's info"""
        return f"{self.name} - {self.age}, {self.profession}"

    def join_alliance(self, alliance):
        self.alliances.append(alliance.name)

    def leave_alliance(self, alliance_name):
        if alliance_name in self.alliances:
            self.alliances.remove(alliance_name)
